#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Copyright (c) 2020, MrDoob
# All rights reserved.

# shellcheck disable=SC2086
# umask 022
# command="/app/cleanup/cleanup.sh"
# sleep 10
# echo "-> Starting cleaning garbage files<-"
# exec s6-setuidgid abc $command
