#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Copyright (c) 2020, MrDoob
# All rights reserved.

# shellcheck disable=SC2086

umask 022
mount_command="/app/mergerfs.sh"
sleep 5s

echo "-> Starting mergerfs <-"
exec $mount_command