#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Copyright (c) 2019, PhysK
# All rights reserved.

# shellcheck disable=SC2086

umask 022
vnstat_command="vnstat"
echo "-> Starting vnstat <-"
exec s6-setuidgid abc $vnstat_command