#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Copyright (c) 2019, PhysK
# All rights reserved.

# shellcheck disable=SC2086
umask 022
plex_command="/app/plex/plex.sh"
sleep 10s
echo "-> Starting plex streams checker <-"
exec s6-setuidgid abc $plex_command
