#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Copyright (c) 2020, MrDoob 
# All rights reserved.

# shellcheck disable=SC2086
umask 022
uploader_command="/app/serverside/serverside.sh"
sleep 10s
echo "-> Starting server side <-"
exec s6-setuidgid abc $uploader_command
