#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Copyright (c) 2020, MrDoob
# All rights reserved.

# shellcheck disable=SC2086
umask 022
serverside_command="/app/serverside/serverside.sh"
sleep 3
echo "-> Starting Server-Side Uploader <-"
exec $serverside_command
