#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Copyright (c) 2020, MrDoob
# All rights reserved.
function log() {
echo "[Uploader] ${1}"
}

rclone_base=/config/rclone.conf
if [ ! -f ${rclone_base} ]; then
   log "-->> [ WARNING ] no rclone.conf file found [ WARNING ] <<--"
   sleep 60
   exit 1
fi

rclone_docker=/config/rclone-docker.conf
rclone_base=/config/rclone.conf
if [ -f ${rclone_base} ]; then
  log "-> Copying rclone.conf <-"
      rm -f ${rclone_docker}
      cp ${rclone_base} ${rclone_docker}
  log "-> Make needed edits to rclone-docker.conf <-"
      sed -i "s#/opt/appdata/plexguide/.blitzkeys/#/config/keys/#g" ${rclone_docker}
      sed -i "s#/opt/appdata/uploader/#/config/keys/#g" ${rclone_docker}
      sed -i "s#/opt/appdata/services/uploader/keys/#/config/keys/#g" ${rclone_docker}
      sed -i "s#/opt/uploader/keys/#/config/keys/#g" ${rclone_docker}
      sed -i '/pgunion/{n;N;d;}' ${rclone_docker}
      sed -i '/pgunion/d' ${rclone_docker}
  log "-> rclone_docker.conf edits done <-"
fi
rclone_bin=/usr/bin/rclone
if [ ! -f ${rclone_bin} ]; then
  log "-> install rclone || start <-"
      wget https://downloads.rclone.org/rclone-current-linux-amd64.zip -O rclone.zip >/dev/null 2>&1 && \
      unzip -qq rclone.zip && rm rclone.zip && \
      mv rclone*/rclone /usr/bin && rm -rf rclone* 
  log "-> install rclone || done <-"
fi
