#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Copyright (c) 2020, MrDoob
# All rights reserved.
function log() {
echo "[Mount] ${1}"
}

apk add --quiet --no-cache --no-progress --virtual build-dependencies \
  wget curl bash unzip
wget --quiet https://beta.rclone.org/rclone-beta-latest-linux-amd64.zip -O rclone.zip && \
unzip -q rclone.zip && rm rclone.zip && \
mv rclone*/rclone /usr/bin && rm -r rclone*

if [ -f "/config/rclone.conf" ]; then
   rclone config dump --config=/config/rclone.conf > /config/rclone.json
   #rm -rf /config/rclone.conf
fi
if [ ! -f "/config/rclone.josn" ]; then
   log "-->> [ WARNING ] no rclone.josn file found [ WARNING ] <<--"
   sleep 60
   s6-svscanctl -t /var/run/s6/services
fi
log "-> Copying rclone.json <-"
    rclonepad=/config/rclone/rclone-docker.json 
    mkdir -p /config/rclone
    rm -f ${rclonepad}
    find /config -name "rclone.json" -type f -exec cp {} ${rclonepad} \;
    log "-> Make needed edits to rclone-docker.json <-"
    sed -i "s#/opt/appdata/plexguide/.blitzkeys/#/config/keys/#g" /config/rclone/rclone-docker.json
    sed -i "s#/opt/appdata/uploader/#/config/keys/#g" /config/rclone/rclone-docker.json
    sed -i "s#/opt/appdata/services/uploader/keys/#/config/keys/#g" /config/rclone/rclone-docker.json
    sed -i "s#/opt/uploader/keys/#/config/keys/#g" /config/rclone/rclone-docker.json
    sed -i '/pgunion/{n;N;d;}' /config/rclone/rclone-docker.json
    sed -i '/pgunion/d' /config/rclone/rclone-docker.json
log "-> rclone_docker.conf edits done <-"


#<EOF>#
