#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Copyright (c) 2020, MrDoob
# All rights reserved.

TARGET_FOLDER='/etc/services.d/{uploader-gdrive,uploader-tdrive,serverside,cleaning}'
FIND=$(which find)
FIND_BASE='-type f'
FIND_FILE='"down"'
FIND_FILE_ACTION='-name'
FIND_MINDEPTH='-mindepth 1'
FIND_ACTION='-delete 1>/dev/null 2>&1'
command="${FIND} ${TARGET_FOLDER} ${FIND_MINDEPTH} ${FIND_FILE_ACTION} ${FIND_FILE} ${FIND_BASE} ${FIND_ACTION}"
eval ${command}

if grep -q GDSA01 /config/rclone/rclone-docker.conf && grep -q GDSA02 /config/rclone/rclone-docker.conf; then
    echo "-->> -------------------- <<--"
    echo "-->    TDRIVE UPLOADER    <<--"
    echo "-->       WILL USED       <<--"
    echo "-->> -------------------- <<--"
else
    echo "-->> ---------------------------------------- <<--"
    echo "-->  I DONT SUPPORT GDRIVE UPLOADER ANYMORE   <<--"
    echo "-->> ---------------------------------------- <<--"
    exit 0
fi

CLEANUPDOWN=${CLEANUPDOWN}

if [ "${CLEANUPDOWN}" == 'down' ] || [ "${CLEANUPDOWN}" == 'false' ]; then
   touch /etc/services.d/cleaning/down
   echo " [ USER WISH ACTION ] "
   echo "   Shutdown Cleaning  "
   echo " [ USER WISH ACTION ] "
   sleep 10
else 
   echo " [ USER WISH ACTION ] "
   echo "   Starting Cleaning  "
   echo " [ USER WISH ACTION ] "
   sleep 5
fi
