#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Copyright (c) 2020, MrDoob
# All rights reserved.

TARGET_FOLDER='/etc/services.d/{uploader-gdrive,uploader-tdrive,serverside}'
FIND=$(which find)
FIND_BASE='-type f'
FIND_FILE='"down"'
FIND_FILE_ACTION='-name'
FIND_MINDEPTH='-mindepth 1'
FIND_ACTION='-delete 1>/dev/null 2>&1'
command="${FIND} ${TARGET_FOLDER} ${FIND_MINDEPTH} ${FIND_FILE_ACTION} ${FIND_FILE} ${FIND_BASE} ${FIND_ACTION}"
eval ${command}

if grep -q GDSA01 /config/rclone-docker.conf && grep -q GDSA02 /config/rclone-docker.conf; then
    touch /etc/services.d/uploader-gdrive/down
else
    touch /etc/services.d/uploader-tdrive/down
fi
