#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Copyright (c) 2020, MrDoob
# All rights reserved.
## function source
function log() {
echo "[Uploader] ${1}"
}
log "-> Setting Permissions || start <-"

mkdir -p /config/{discord,env}
find /mnt/downloads -exec chmod a=rx,u+w {} \;
find /mnt/downloads -exec chown -hR abc:abc {} \;

find /config -exec chmod a=rx,u+w {} \;
find /config -exec chown -hR abc:abc {} \;
find /app -exec chmod a=rx,u+w {} \;
find /app -exec chown -hR abc:abc {} \;

chown -R abc:abc /run \
          /var/lib/nginx \
          /var/log/nginx \
          /var/www

if [[ $(command -v rclone | wc -l) == "1" ]]; then
    chown -cf abc:abc /root
fi
log "-> Setting Permissions || done <-"
#EOF
