#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Copyright (c) 2020, MrDoob
# All rights reserved.
function log() {
echo "[Uploader] ${1}"
}
DISABLE_GDRIVE=${DISABLE_GDRIVE:-false}
UFSTMP=$(cat /tmp/ufstmp.path)
if [ "${DISABLE_GDRIVE}" == "true" ] || ! grep -q gdrive /config/rclone-docker.conf; then
    touch /etc/services.d/mount-gdrive/down
    log "-> Disabled Gdrive Mount <-"
else
    echo "${UFSTMP}:/mnt/gdrive=NC" > /tmp/ufs.path
fi
