#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Copyright (c) 2019, PhysK
# All rights reserved.
function log() {
echo "[Uploader] ${1}"
}
DISABLE_WEB=${DISABLE_WEB:-false}
if [ "${DISABLE_WEB}" == "true" ]; then
    touch /etc/services.d/php-fpm/down
    touch /etc/services.d/nginx/down
    log "-> Disabled Web Tracker <-"
fi
