#!/usr/bin/with-contenv bash
# shellcheck shell=bash
function log() {
echo "[Uploader] ${1}"
}

log "-> update packages || start <-"
 apk update -qq && apk upgrade -qq && apk fix -qq
echo "@daily /app/update-alpine/update-alpine.sh" > /crontab.conf
crontab /crontab.conf
log "-> update packages || done <-"