#!/usr/bin/with-contenv bash
# shellcheck shell=bash
function log() {
echo "[Uploader] ${1}"
}

log "-> update packages || start <-"
apk --no-cache update -qq && apk --no-cache upgrade -qq && apk --no-cache fix -qq
echo "@daily /app/update-alpine/update-alpine.sh" > /crontab.conf
crontab /crontab.conf
log "-> update packages || done <-"