#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Copyright (c) 2020, MrDoob
# All rights reserved.
function log() {
echo "[Uploader] ${1}"
}
function vnstat_install() {
vnstat=/etc/vnstat.conf
if [ ! -f ${vnstat} ]; then
   log "-> install vnstat || start <-"
   apk --no-cache update -qq && apk --no-cache upgrade -qq && apk --no-cache fix -qq
   apk add vnstat -qq
   rm -rf /var/cache/apk/*
   sed -i 's/Interface ""/Interface "eth0"/g' /etc/vnstat.conf
   sed -i 's/UnitMode 0/UnitMode 1/g' /etc/vnstat.conf
   sed -i 's/RateUnit 1/RateUnit 0/g' /etc/vnstat.conf
   sed -i 's/Locale "-"/Locale "LC_ALL=en_US.UTF-8"/g' /etc/vnstat.conf
   log "-> install vnstat || done <-"
else
   sed -i 's/Interface ""/Interface "eth0"/g' /etc/vnstat.conf
   sed -i 's/UnitMode 0/UnitMode 1/g' /etc/vnstat.conf
   sed -i 's/RateUnit 1/RateUnit 0/g' /etc/vnstat.conf
   sed -i 's/Locale "-"/Locale "LC_ALL=en_US.UTF-8"/g' /etc/vnstat.conf
   log "-> package vnstat already installed <-"
fi
}

vnstat_install