#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Copyright (c) 2020, MrDoob
# All rights reserved.
function log() {
    echo "[Server Side] ${1}"
}
RCLONEDOCKER=/config/rclone-docker.conf
SERVERSIDECHECK=$(cat ${RCLONEDOCKER} | awk '$1 == "server_side_across_configs" {print $3}' | wc -l)
SERVERSIDE=${SERVERSIDE}
downcommand=/etc/services.d/serverside/down

if [ -e ${downcommand} ]; then
   rm -rf ${downcommand}
fi

if [ "${SERVERSIDE}" != 'false' ] || [ "${SERVERSIDECHECK}" != 'down' ]; then 
   log "-> Server_side will be used <-"
else
   log "-> Server_side skipped <- "
   touch ${downcommand}
fi
#EOF