#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Copyright (c) 2020, MrDoob
# All rights reserved.
function log() {
    echo "[Server Side] ${1}"
}
RCLONEDOCKER=/config/rclone/rclone-docker.conf
SERVERSIDE=${SERVERSIDE}

if [ "${SERVERSIDE}" != 'false' ] || [ "${SERVERSIDE}" != 'down' ]; then 
   log "-> Server_side will be used <-"
else
   log "-> Server_side skipped <- "
   touch /etc/services.d/serverside/down
fi
#EOF