#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Copyright (c) 2019, PhysK
# All rights reserved.

RCLONEDOCKER="/config/rclone-docker.conf"
if grep -q server_side** ${RCLONEDOCKER} ; then
   echo "-> Server_side works  <-"
else 
   touch /etc/services.d/serverside/down
fi
