#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# Copyright (c) 2020, MrDoob
# All rights reserved.
function log() {
    echo "[Server Side] ${1}"
}
RCLONEDOCKER=/config/rclone-docker.conf
SERVERSIDECHECK=$(cat ${RCLONEDOCKER} | awk '$1 == "server_side_across_configs" {print $3}' | wc -l)
if [[ "${SERVERSIDECHECK}" -gt "1" ]]; then 
   log "-->> Server_side is added <<-- "
 if grep -q "\[tcrypt\]" ${RCLONEDOCKER} && grep -q "\[gcrypt\]" ${RCLONEDOCKER}; then
     log " -->> Check for booth salt passwords <<--"
     rccommand1=$(rclone reveal $(cat ${RCLONEDOCKER} | awk '$1 == "password" {print $3}' | head -n 1 | tail -n 1))
     rccommand2=$(rclone reveal $(cat ${RCLONEDOCKER} | awk '$1 == "password" {print $3}' | head -n 2 | tail -n 1))
     rccommand3=$(rclone reveal $(cat ${RCLONEDOCKER} | awk '$1 == "password2" {print $3}' | head -n 1 | tail -n 1))
     rccommand4=$(rclone reveal $(cat ${RCLONEDOCKER} | awk '$1 == "password2" {print $3}' | head -n 2 | tail -n 1))
   if [[ "${rccommand1}" == "${rccommand2}" && "${rccommand3}" == "${rccommand4}" ]]; then
      log "   --->> Server_side can be used <<--- "
      if [[ "${SERVERSIDE}" != "true" ]]; then
         log "   --->> SET DOCKER Env SERVERSIDE to true <<--- "
         sleep 10
      fi
      log "   --->> TCrypt and GCrypt used the same password <<--- "
   else
      log "   --->> Server_side can't be used <<--- "
      log "   --->> TCrypt and GCrypt dont used the same password <<--- "
   fi
  fi
else
   log " --->> Server_side is not included <<--- "
   log " --->> skipping <<--- "
fi
sleep 10
